kind: pipeline
type: docker
name: catapp by HS

steps:
  - name: unit tests
    image: cirrusci/flutter:2.5.3
    commands:
      - flutter pub get
      - sdkmanager "system-images;android-27;google_apis_playstore;x86"
      - flutter emulators --create "test"
      - flutter emulators
      - flutter emulators --launch flutter_emulator
      - flutter devices
      - flutter test integration_test
