kind: pipeline
type: docker
name: catapp by HS

steps:
  - name: generate code
    image: cirrusci/flutter:2.5.3
    commands:
      - flutter pub get
      - flutter pub run build_runner build --delete-conflicting-outputs
