kind: pipeline
type: docker
name: catapp by HS

steps:
  - name: unit tests
    image: cirrusci/flutter:2.5.3
    commands:
      - flutter pub get
      - flutter test -d emulator-5554 --machine --version integration_test integration_test
